# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: metadata/v1/metadata.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'metadata/v1/metadata.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ametadata/v1/metadata.proto\x12\x0bmetadata.v1\"<\n\x13\x41nalyzeImageRequest\x12\x13\n\x0bimage_bytes\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\"G\n\x14\x41nalyzeImageResponse\x12\x0f\n\x07\x63\x61ption\x18\x01 \x01(\t\x12\x10\n\x08ocr_text\x18\x02 \x01(\t\x12\x0c\n\x04tags\x18\x03 \x03(\t2f\n\x0fMetadataService\x12S\n\x0c\x41nalyzeImage\x12 .metadata.v1.AnalyzeImageRequest\x1a!.metadata.v1.AnalyzeImageResponseB.Z,iris/internal/metadata/metadatav1;metadatav1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'metadata.v1.metadata_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z,iris/internal/metadata/metadatav1;metadatav1'
  _globals['_ANALYZEIMAGEREQUEST']._serialized_start=43
  _globals['_ANALYZEIMAGEREQUEST']._serialized_end=103
  _globals['_ANALYZEIMAGERESPONSE']._serialized_start=105
  _globals['_ANALYZEIMAGERESPONSE']._serialized_end=176
  _globals['_METADATASERVICE']._serialized_start=178
  _globals['_METADATASERVICE']._serialized_end=280
# @@protoc_insertion_point(module_scope)
