# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: clip/v1/clip.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'clip/v1/clip.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63lip/v1/clip.proto\x12\x07\x63lip.v1\" \n\x10\x45mbedTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"(\n\x11\x45mbedImageRequest\x12\x13\n\x0bimage_bytes\x18\x01 \x01(\x0c\"/\n\rEmbedResponse\x12\x11\n\tembedding\x18\x01 \x03(\x02\x12\x0b\n\x03\x64im\x18\x02 \x01(\x05\x32\x8f\x01\n\x0b\x43lipService\x12>\n\tEmbedText\x12\x19.clip.v1.EmbedTextRequest\x1a\x16.clip.v1.EmbedResponse\x12@\n\nEmbedImage\x12\x1a.clip.v1.EmbedImageRequest\x1a\x16.clip.v1.EmbedResponseB\"Z iris/internal/clip/clipv1;clipv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'clip.v1.clip_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z iris/internal/clip/clipv1;clipv1'
  _globals['_EMBEDTEXTREQUEST']._serialized_start=31
  _globals['_EMBEDTEXTREQUEST']._serialized_end=63
  _globals['_EMBEDIMAGEREQUEST']._serialized_start=65
  _globals['_EMBEDIMAGEREQUEST']._serialized_end=105
  _globals['_EMBEDRESPONSE']._serialized_start=107
  _globals['_EMBEDRESPONSE']._serialized_end=154
  _globals['_CLIPSERVICE']._serialized_start=157
  _globals['_CLIPSERVICE']._serialized_end=300
# @@protoc_insertion_point(module_scope)
