// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v6.33.0
// source: metadata/v1/metadata.proto

package metadatav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyzeImageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageBytes []byte `protobuf:"bytes,1,opt,name=image_bytes,json=imageBytes,proto3" json:"image_bytes,omitempty"`
	Filename   string `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
}

func (x *AnalyzeImageRequest) Reset() {
	*x = AnalyzeImageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metadata_v1_metadata_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnalyzeImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeImageRequest) ProtoMessage() {}

func (x *AnalyzeImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_v1_metadata_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeImageRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeImageRequest) Descriptor() ([]byte, []int) {
	return file_metadata_v1_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeImageRequest) GetImageBytes() []byte {
	if x != nil {
		return x.ImageBytes
	}
	return nil
}

func (x *AnalyzeImageRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type AnalyzeImageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Caption string   `protobuf:"bytes,1,opt,name=caption,proto3" json:"caption,omitempty"`
	OcrText string   `protobuf:"bytes,2,opt,name=ocr_text,json=ocrText,proto3" json:"ocr_text,omitempty"`
	Tags    []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *AnalyzeImageResponse) Reset() {
	*x = AnalyzeImageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metadata_v1_metadata_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnalyzeImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeImageResponse) ProtoMessage() {}

func (x *AnalyzeImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_v1_metadata_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeImageResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeImageResponse) Descriptor() ([]byte, []int) {
	return file_metadata_v1_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyzeImageResponse) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

func (x *AnalyzeImageResponse) GetOcrText() string {
	if x != nil {
		return x.OcrText
	}
	return ""
}

func (x *AnalyzeImageResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_metadata_v1_metadata_proto protoreflect.FileDescriptor

var file_metadata_v1_metadata_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x22, 0x52, 0x0a, 0x13, 0x41, 0x6e, 0x61,
	0x6c, 0x79, 0x7a, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x42, 0x79, 0x74, 0x65,
	0x73, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x5f, 0x0a,
	0x14, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x61, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x61, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x19, 0x0a, 0x08, 0x6f, 0x63, 0x72, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6f, 0x63, 0x72, 0x54, 0x65, 0x78, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61,
	0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x32, 0x66,
	0x0a, 0x0f, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x53, 0x0a, 0x0c, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x12, 0x20, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e,
	0x41, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x76,
	0x31, 0x2e, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2e, 0x5a, 0x2c, 0x69, 0x72, 0x69, 0x73, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x2f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x76, 0x31, 0x3b, 0x6d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_metadata_v1_metadata_proto_rawDescOnce sync.Once
	file_metadata_v1_metadata_proto_rawDescData = file_metadata_v1_metadata_proto_rawDesc
)

func file_metadata_v1_metadata_proto_rawDescGZIP() []byte {
	file_metadata_v1_metadata_proto_rawDescOnce.Do(func() {
		file_metadata_v1_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(file_metadata_v1_metadata_proto_rawDescData)
	})
	return file_metadata_v1_metadata_proto_rawDescData
}

var file_metadata_v1_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_metadata_v1_metadata_proto_goTypes = []interface{}{
	(*AnalyzeImageRequest)(nil),  // 0: metadata.v1.AnalyzeImageRequest
	(*AnalyzeImageResponse)(nil), // 1: metadata.v1.AnalyzeImageResponse
}
var file_metadata_v1_metadata_proto_depIdxs = []int32{
	0, // 0: metadata.v1.MetadataService.AnalyzeImage:input_type -> metadata.v1.AnalyzeImageRequest
	1, // 1: metadata.v1.MetadataService.AnalyzeImage:output_type -> metadata.v1.AnalyzeImageResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_metadata_v1_metadata_proto_init() }
func file_metadata_v1_metadata_proto_init() {
	if File_metadata_v1_metadata_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_metadata_v1_metadata_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnalyzeImageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metadata_v1_metadata_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnalyzeImageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_metadata_v1_metadata_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metadata_v1_metadata_proto_goTypes,
		DependencyIndexes: file_metadata_v1_metadata_proto_depIdxs,
		MessageInfos:      file_metadata_v1_metadata_proto_msgTypes,
	}.Build()
	File_metadata_v1_metadata_proto = out.File
	file_metadata_v1_metadata_proto_rawDesc = nil
	file_metadata_v1_metadata_proto_goTypes = nil
	file_metadata_v1_metadata_proto_depIdxs = nil
}
